codecov:
  notify:
    require_ci_to_pass: yes
  token: secret:Z/PFiiaF+BZvfwjD9BBZob0j/tedL2QQVJSirFmIY52mqhRt3JlKe393j1Kw6mFDW/M/IqlQx8CmQ0j9lYog/pb1gvimvK3g//aS09cV93Y=
  
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no