# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/api-server
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: pwd && go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run: bash <(curl -s https://codecov.io/bash) -t 'secret:Z/PFiiaF+BZvfwjD9BBZob0j/tedL2QQVJSirFmIY52mqhRt3JlKe393j1Kw6mFDW/M/IqlQx8CmQ0j9lYog/pb1gvimvK3g//aS09cV93Y='
workflows:
  version: 2
  build:
    jobs:
      - build